# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[pip] "
    target-branch: "upgrade-packages"
    reviewers:
      - "Serious-senpai"

  - package-ecosystem: "npm"
    directory: "/bot/web"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm] "
    target-branch: "upgrade-packages"
    reviewers:
      - "Serious-senpai"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Actions] "
    target-branch: "upgrade-packages"
    reviewers:
      - "Serious-senpai"
