from .ava import *
from .help import *
from .info import *
from .miku_or_fubuki import *
from .otp import *
from .ping import *
from .prefix import *
from .render import *
from .say import *
from .source import *
from .speak import *
from .svinfo import *
