# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"

      - name: View Flutter status
        run: |
          flutter --version
          flutter doctor -v

      - name: Initialize web project
        run: flutter create --platforms web --project-name haruka bot/web

      - name: Build front-end server
        working-directory: bot/web
        run: flutter build web --output ../server/build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: haruka-build
          path: .

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: haruka-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: haruka39
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
